title: Products
modelClass: CanThis\MLRepeaterTest\Models\Product
list: $/canthis/mlrepeatertest/models/product/columns.yaml
recordUrl: 'canthis/mlrepeatertest/products/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
